spring:
  application:
    name: vk-springboot-jooq-kotlin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

